#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\factions.bof
BOFS  = duke.bof princess.bof rebel.bof koccitalmo.bof shally.bof queenven.bof

!include $(KODDIR)\kod.mak
