#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\key.bof
BOFS = sanctkey.bof barloquekey.bof basementkey.bof castlekey.bof \
	   cornothkey.bof throne1key.bof throne2key.bof toskey.bof

!include $(KODDIR)\kod.mak
