#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\soldierqt.bof
BOFS = cesssoldierqt.bof dukesoldierqt.bof rebelsoldierqt.bof \
       kocsoldierqt.bof unholysoldierqt.bof holysoldierqt.bof

!include $(KODDIR)\kod.mak
