#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\weed.bof
BOFS = farenc.bof jalac.bof kranc.bof qorc.bof riijac.bof shalc.bof weaponsc.bof

!include $(KODDIR)\kod.mak
