#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\weapon.bof
BOFS =  shrtswrd.bof mystswrd.bof mace.bof bkdagger.bof spirhamm.bof\
        scimitar.bof longswrd.bof hammer.bof ranged.bof axe.bof goldswrd.bof \
        riijaswd.bof neruswd.bof huntsw.bof unique.bof testswrd.bof \
        neruaxe.bof twinblade.bof lightsword.bof maul.bof bersaxe.bof pickaxe.bof \
        basewand.bof weapwand.bof cuttingaxe.bof sickel.bof \

!include $(KODDIR)\kod.mak
