#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\soldshld.bof

BOFS = \
   prinshld.bof dukeshld.bof reblshld.bof necshield.bof holyshield.bof kocshield.bof

!include $(KODDIR)\kod.mak
