#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\utility.bof
BOFS = set.bof loadout.bof conveyance.bof phase.bof meditate.bof transference.bof \
       vaultloadout.bof donate.bof camp.bof \

!include $(KODDIR)\kod.mak
