#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\servant.bof
BOFS  = servkran.bof servshal.bof servqor.bof servriija.bof servjala.bof servfaren.bof

!include $(KODDIR)\kod.mak
