#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\servant.bof
BOFS  = servantkran.bof servantshal.bof servantqor.bof servantriija.bof servantjala.bof \
        servantfaren.bof \

!include $(KODDIR)\kod.mak
