#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\helmet.bof
BOFS = helm.bof circlet.bof ivycircl.bof simphelm.bof mask.bof qormashelm.bof \
       dhelm.bof wizardhat.bof steelhelm.bof warhelm.bof legionhelm.bof \
       knighthelm.bof bloodcirclet.bof

!include $(KODDIR)\kod.mak
