#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\summonservant.bof
BOFS = servantqor.bof servantshal.bof servantkran.bof servantfaren.bof servantriija.bof \
       servantjala.bof

!include $(KODDIR)\kod.mak
