#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\deathrealm.bof

BOFS =  dh4.bof dh3.bof di3.bof dbarls.bof dbarln.bof dbarlport.bof \
		dj3.bof dcastle2b.bof dbadland2.bof dbadland1.bof dk5.bof dh5.bof \
		dh6.bof dtos.bof deasttos.bof dtosgrave.bof dtoscrypt.bof dduke1.bof

!include $(KODDIR)\kod.mak

