#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\factflag.bof
BOFS = dukeflag.bof prncflag.bof reblflag.bof holyflag.bof unholyflag.bof kocflag.bof

!include $(KODDIR)\kod.mak
