#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\deathrealmM.bof
BOFS  = vajra.bof revenantb.bof chimera.bof cyclops.bof followerofqor.bof \
		minotaurbeserker.bof Tyrant.bof fallenmonk.bof hellwasp.bof vozun.bof \
		croco.bof dulahan.bof grandpatrent.bof



!include $(KODDIR)\kod.mak
