#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\factionmage.bof
BOFS  = prinmage.bof dukemage.bof holymage.bof unholymage.bof kocmage.bof jonasmage.bof


!include $(KODDIR)\kod.mak
